feat: add support to archive repositories
pulumiverse/infra pull request #226
Opened 2024-09-28 13:51 UTC by dirien

This PR add support to archive a provider.

2024-09-28 13:52 UTC, dirien commented
Not sure why both jobs are failing. 🤔

2024-09-28 14:55 UTC, tmeckel commented
> Not sure why both jobs are failing. 🤔

@dirien it's because you want to merge a branch from a fork. The repo is still not configured in a way that secrets are passed to workflow runs that started from a fork. This is an outstanding issue that @ringods and I worked upon but never came to a satisfiable solution.

2024-09-28 15:08 UTC, dirien commented
@tmeckel: I have no permission to create a branch in this repo.

2024-09-28 15:11 UTC, tmeckel commented
@dirien no need to close the PR. I'll review and merge when I've time. Sorry if my initial answer was misunderstandable in that way.

2024-09-28 15:12 UTC, dirien commented
@tmeckel sounds good! Thanks!

2024-09-28 21:52 UTC, tmeckel requested changes
I would set `hasIssues` to `false`, if a repository is archived `hasIssues:  args.archived === true ? false : true`. Because it makes no sense to enable issues on an archived repository.

Same with `vulnerabilityAlerts`: `vulnerabilityAlerts: args.archived === true ? false : true,`

2024-09-28 21:52 UTC, tmeckel commented on src/github/repositories.ts
> +                    archived: repositoryInfo.archived || false,
Should be `archived: repository.archived === true ? true : false,`

2024-09-28 21:52 UTC, tmeckel commented on src/github/repositories.ts
> +                    archived: repositoryInfo.archived || false,
Should be archived: `repository.archived === true ? true : false,`

2024-09-28 21:52 UTC, tmeckel commented on src/github/repositories.ts
> +                archived: args.archived || false
Should be archived: `args.archived === true ? true : false,`

2024-09-28 22:00 UTC, dirien commented
@tmeckel done

2024-09-29 15:30 UTC, tmeckel commented
Approved, after running `pulumi preview` locally with the following result

![image](https://github.com/user-attachments/assets/7c100880-8eec-4431-944d-3c4f5b225a2b)

2024-09-29 15:31 UTC, merged