Adding dbhagen as a contributor for and with the pulumi-fortios provider
pulumiverse/infra pull request #65
Opened 2023-06-01 15:51 UTC by dbhagen

This PR will create a new repository for the Fortinet FortiOS Provider.

2023-06-01 19:22 UTC, ringods requested changes

2023-06-01 19:22 UTC, ringods commented on 03-members/dbhagen.yaml
> +push:
@dbhagen you can only have one level of permissions for a certain repo, so keep `maintain` for `pulumi-fortios`.

2023-06-01 19:29 UTC, dbhagen commented
Sorry about that, @ringods. Updated.

2023-06-02 07:27 UTC, ringods approved these changes

2023-06-02 07:28 UTC, merged